INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://www.wuxiaworld.com/feed/','Skyfire Avenue',NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://totobro.com/feed/',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://radianttranslations.com/feed/','The Legend of the Dragon King',NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://cookiepasta.com/feed/',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://bluesilvertranslations.wordpress.com/feed/',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/onepunch_man.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/one_piece.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/fairy_tail.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/douluo_dalu.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/nanatsu_no_taizai.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/shen_yin_wang_zuo.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://mangafox.me/rss/douluo_dalu_ii_jueshui_tangmen.xml',NULL,NULL);
INSERT INTO "sendto" VALUES('kieran@kcolford.com','http://xkcd.com/rss.xml',NULL,NULL);
